apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-agent
  namespace: operant
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      serviceAccountName: kube-agent
      containers:
        - name: kube-agent
          image: agent
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: kube-agent-entrypoint
  namespace: operant
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001