// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeployJobInput struct {
	Name         string `json:"name"`
	Namespace    string `json:"namespace"`
	Image        string `json:"image"`
	Command      string `json:"command"`
	BackOffLimit int    `json:"backOffLimit"`
}

type Mutation struct {
}

type Query struct {
}
